global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['rabbitmq-exporter:15692']

  - job_name: 'service'
    static_configs:
      - targets: ['pushgateway:9091']
