
services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "60000:8080"  
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root 
    restart: unless-stopped

volumes:
  jenkins_home:

