pipeline {
    agent any

    environment {
        COMPOSE_FILE = 'compose.yml'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Tawunchai/serverless-cloud.git'
            }
        }

        stage('Check prometheus.yml') {
            steps {
                script {
                    def filePath = '/var/jenkins_home/workspace/C4/prometheus.yml'
                    
                    // เช็คว่าไฟล์มีอยู่หรือไม่
                    if (fileExists(filePath)) {
                        echo "File exists: ${filePath}"
                    } else {
                        error "File does not exist: ${filePath}. Please check the file path."
                    }
                }
            }
        }

        stage('Stop Old Containers?') {
            steps {
                sh 'docker-compose -f ${COMPOSE_FILE} down || true'
            }
        }

        stage('Build & Start Containers.') {
            steps {
                sh 'docker-compose -f ${COMPOSE_FILE} build'
                sh 'docker-compose -f ${COMPOSE_FILE} up -d'
            }
        }
    }
}
